Implemented environment generation feature. (#15)
* now make the following page:
/site/environment

all the information of t

* on the /site/environment page. show card instead of the table view forma

* Runtime Error

Error: Can't find variable: CardContent
src/app/(manage)

* use of excessive cards.
only one title per page.

then we don't need a b

* now pagination, implement pagination of 10 per page, and then next and b