Updated the deployment engine. (#16)
* implement the same design changes on the /site/deploy

* keep only one column.

* no gap on deploy all changes.
add some gap before the deploy all changes

* Runtime Error

Error: Can't find variable: getLastDeployment
src/app/(m

* Error Details
ID: TNuZcS8JP0gg9osNPW4V
Timestamp: 03/01/2026, 00:04:55
M

* Function addDoc() called with invalid data. Unsupported field value: und

* the .env is not being created.
what we need to do is the following.

del

* the command used to deploy, show that on the commands, because we're doi

* Updated the structure deployment.

* Internal Error: Connecting to 3.7.241.26 to upload data...
Connected. Pr

* why the fuck are you making the /Users/neupkishor/Documents/neupsites fo