Implemented a proper site switching enhancement. (#17)
* make a new page called as /switch instead of /auth.

this will work 2 wa

* Build Error

Module not found: Can't resolve '@/actions/sites'
./src/app

* on the sidebar show, switch and not switch account.

make the change.

* on the /switch page, show the page in left alignment and then show the p

* when a siteid is selected, in the switch page, show selected on the page

* Runtime Error

Error: Can't find variable: CardFooter
src/app/(manage)/

* on the /switch page. show all the sites but on the site that we're curre

* now we don't need the /auth page.
if the user is not logged in take the

* now when the siteid has been selected, show the status page, the site ba